### ISSUE TITLE
CI tests are running against legacy node

### ISSUE THREAD

**Issue by amilajack** [medikoo/memoizee#101]
<img width="1126" alt="screen shot 2018-09-24 at 10 21 45 pm" src="https://user-images.githubusercontent.com/6374832/45994398-4bff4900-c048-11e8-8249-24e25e24fdd0.png">

**Comment by medikoo** [comment]
Indeed configuration was not updated. Fixed now -> https://ci.appveyor.com/project/medikoo/memoizee

Thanks!
