### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by stovak** [medikoo/memoizee#107]
File does not exist in latest version of this module:

require("es5-ext/object/normalize-options")

Throwing errors.

https://github.com/medikoo/memoizee/blob/a3bb4beae8ec2940f5f6c837f7993cbf2e7c7729/index.js#L3

**Comment by medikoo** [comment]
@stovak there must be some issue with you're setup. Given module exists in `es5-ext` -> https://github.com/medikoo/es5-ext/blob/v0.10.53/object/normalize-options.js
