### ISSUE TITLE
Cannot find module 'event-emitter'

### ISSUE THREAD

**Issue by perstromswe** [medikoo/memoizee#111]
When I try to run my app on azure windows I get:

Mon May 11 2020 18:18:23 GMT+0000 (Greenwich Mean Time): Application has thrown an uncaught exception and is terminated:
Error: Cannot find module 'event-emitter'
Require stack:
- D:\home\site\wwwroot\dist\node_modules\memoizee\lib\configure-map.js

Maybe event-emitter should be replaced with something?

**Comment by medikoo** [comment]
@perstromswe Ensure to install your project with `npm install`. `event emitter` is listed as one of the project dependencies

**Comment by perstromswe** [comment]
I have run npm install (npm ci). The project has around 50 dependencies. If I remove the email-templates package which uses the memoizee pacakage, the app works in windows azure. Wierd since it works on my dev-machine. So it must be something windows-related.

**Comment by medikoo** [comment]
@perstromswe On windows `npm` should also work without issues. 

I take it's some issue with your Azure setup, and you probably should seek help on some Azure forum. 

I'm going to close this as it's definitely not a problem with `memoizee`
