### ISSUE TITLE
Dependency on "D" renders this useless

### ISSUE THREAD

**Issue by mssngr** [medikoo/memoizee#112]
Whoever maintains the `d` package just pulled their code from NPM. `memoizee`, which depends on `d` can no longer be used, except with someone who hasn't wiped their `node_modules` recently.

**Comment by mssngr** [comment]
Update, looks like you maintain `d`? Could you add it back?

**Comment by medikoo** [comment]
@mssngr `d` was not pulled, it's actually a continusly maintained project. https://www.npmjs.com/package/d

I guess there's some issue on your side, or some issues with npm registry currently

**Comment by mssngr** [comment]
Perhaps an issue with npm registry? We can keep up the conversation in the Issue I created for `d`. https://github.com/medikoo/d/issues/16

Pasted from the issue in `d`:
![Screen Shot 2020-06-25 at 1 59 42 PM](https://user-images.githubusercontent.com/23464169/85799127-f152bf80-b6fb-11ea-82c8-28a9fcaab479.png)

```
npm WARN deprecated D@1.0.0: Package no longer supported. Contact support@npmjs.com for more info.
```

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for D@1.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'venona-specs-tools'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p2813835/.npm/_logs/2020-06-25T20_11_16_625Z-debug.log
```

npm debug log
```
1425 silly fetchPackageMetaData error for d@^1.0.1 No matching version found for D@^1.0.1.
```

We were using memoize, which required `d`.

![02_01_16](https://user-images.githubusercontent.com/23464169/85799210-18a98c80-b6fc-11ea-92a4-8c042f584231.jpg)

However, because of `d` no longer existing in NPM, we had to replace all our usage of `memoizee` with `mem`. Multiple teams at my company are having to do the same thing.

**Comment by mssngr** [comment]
Sorry to waste your time! You were right, was a registry issue. We use Artifactory, which mirrors NPM. Someone in the company uploaded a package called `d` with version 1.0.1. And thus, they broke everyone's repos in the whole company 😂.
