### ISSUE TITLE
Doesn't work with snowpack.

### ISSUE THREAD

**Issue by MarkLyck** [medikoo/memoizee#113]
Getting the following error trying to use memoizee with snowpack:

```
Could not load /Users/mark/ypm/xxxx/cloud-one2/node_modules/es5-ext/array/index.js#/e-index-of (imported by node_modules/memoizee/normalizers/get-fixed.js): ENOENT: no such file or directory, open '/Users/mark/ypm/xxxx/cloud-one2/node_modules/es5-ext/array/index.js#/e-index-of'
```

I checked my node modules and `node_modules/es5-ext/array/#/e-index-of.js` exists.

I'm not sure why the import ends up being `es5-ext/array/index.js#/e-index-of` (there is no `index.js` in the require path)

**Comment by medikoo** [comment]
@MarkLyck thanks for report. Still it's an issue in snowpack and memoize, have you tried reporting it over there?

**Comment by MarkLyck** [comment]
added an issue in snowpack for this as well: https://github.com/pikapkg/snowpack/discussions/1159

**Comment by medikoo** [comment]
Thanks, as there's nothing to be done here about that, I'm closing it.
