### ISSUE TITLE
Feature Request: Wouldn't it be good if we could use a Redis backend?

### ISSUE THREAD

**Issue by ATheCoder** [medikoo/memoizee#129]
This can help when an application is running on a cluster and has multiple instances

**Comment by drone1** [comment]
This is exactly what I came here looking for. In my memory, this package already supported a Redis-backed option, so I was a bit shocked that I couldn't find it in the documentation. Such a great package, but for my application, I'd love to be able to NOT have to "warm" every cache on every deploy for every instance in my cluster. Would be a great feature IMO. Any chance this is coming, or any suggestions? Thanks so much!

**Comment by medikoo** [comment]
@ATheCoder v1.0 API once implemented (no ETA, unfortunately) will allow to setup persistent caching

We've discussed that at https://github.com/medikoo/memoizee/issues/33 so I'm going to close that one as duplicate
