### ISSUE TITLE
Hangs NodeJS on shutdown when using maxAge.

### ISSUE THREAD

**Issue by lscpike** [medikoo/memoizee#25]
NodeJs 0.10.33

When I shut down the server it hangs up to the maxAge time before the process exits. Suggests the cache expiry timer is keeping the event loop going.

If I clear the cache explicitly the process exits immediately, but this means I need to track all memoized functions.

**Comment by themaarten** [comment]
How about making 'unreffing' of the timers created by maxAge an extra configuration option? That way the user can decide whether the potential performance penalty is worth it.

**Comment by nevercast** [comment]
I just observed this, currently I'm reducing maxAge to a time I'm willing to wait for the process to exit.

**Comment by puzrin** [comment]
Not sure that listening global kill is the best idea. You may not know how user handle additional signals like SIGHUP/SIGUSR1/SIGUSR2. For example, he may wish to do soft restart of workers in cluster. I'd vote for global method to clear all timeouts (if that possible). That can be useful when soft restart needed.

**Comment by medikoo** [comment]
@puzrin I agree, also It may be totally different case on Windows.

**Comment by puzrin** [comment]
Found: https://nodejs.org/api/timers.html#timers_unref

Timers in memoizee should be "unref-ed". That will do exactly what we need.

**Comment by medikoo** [comment]
@puzrin indeed, great found! We'll follow that then

**Comment by nevercast** [comment]
Not sure if the bug is still around but unref used to cause memory leaks.
I know the npm:odbc-pool module has a .drain() method that clears all the timeouts for use when shutting down your application. That might be some reference.

unref is likely a suitable option, as it's meant to work.

**Comment by puzrin** [comment]
> In the case of setTimeout when you unref you create a separate timer that will wakeup the event loop, creating too many of these may adversely effect event loop performance -- use wisely.

Problem could be in creating too many timeouts. I noted somewhere in another issues, that timer ticks management should be done by single timer object.

**Comment by fampinheiro** [comment]
I'm currently hitting this problem. Do you settled in a solution?

**Comment by medikoo** [comment]
@fampinheiro no it's still not addressed, It will for sure be addressed for v1, but date when that happens is uncertain. PR's are welcome.

**Comment by madnight** [comment]
Same problem here under Arch Linux. The `maxAge` values prevents node from shutdown for the time period defined in `maxAge`.

**Comment by medikoo** [comment]
Fixed following advice by @puzrin from https://github.com/medikoo/memoizee/issues/25#issuecomment-174235094 (not sure why it took me so long, sorry about that).

Published as v0.4.12

**Comment by medikoo** [comment]
On additional note, with v1 there's a plan to not rely on timers at all.
Whether value is stale will be confirmed at invocation. Downside is that cache may grow in memory without control, but that can be further adjusted with `max` setting
