### ISSUE TITLE
`resolvers` are called inconsistently 

### ISSUE THREAD

**Issue by seansfkelley** [medikoo/memoizee#52]
Depending on the length of `resolvers`, they may or may not be called before passing the results to the wrapped function:

```
> m = require('memoizee')
[Function]
// 1-arg, 1-resolver
> m(function(arg) { console.log('arguments:', arg); }, { resolvers: [ () => 'foo' ] })('a')
arguments: a
undefined
// 2-arg, 2-resolver
> m(function(arg1, arg2) { console.log('arguments:', arg1, arg2); }, { resolvers: [ () => 'foo', () => 'bar' ] })('a', 'b')
arguments: foo bar
undefined
// 1-arg, 2-resolver
> m(function(arg) { console.log('arguments:', arg); }, { resolvers: [ () => 'foo', () => 'bar' ] })('a')
arguments: foo
undefined
```

The docs are a little unclear on the exact semantics of `resolvers`, but I take it to mean that the wrapped function should never receive the output of `resolvers` as it is here.

**Comment by medikoo** [comment]
@seanohollaren Firstly, sorry for replying that late, Github notifications failed for me, and it's today I noticed that issue.

What you describe was result of ugly bug. Fixed with https://github.com/medikoo/memoizee/commit/9f86b198f993c0e2469fb8cf151ce5baf09ddadd
Published as v0.3.10

Thank you!
