### ISSUE TITLE
Resolver result is incorrectly passed to function

### ISSUE THREAD

**Issue by Moeriki** [medikoo/memoizee#56]
Since the `0.3.10` update my memoized function incorrectly returns the result of the resolver instead of passing on the input.

My simplified code.

```javascript
const memoized = (func) =>
  memoizee(func, {
    resolvers: [(params) => JSON.stringify(params)],
  })

function queryResource(params) {
  console.log(typeof params, params)
}

const query = memoized(queryResource)

query({ limit: 10 })
```

**Expected**
```
object { limit: 10 } 
```

**Actual**
```
string "{ limit: 10 }"
```

I understand from the commits that a bug in the resolvers has been fixed. Should I update the implementation of my resolver or would this be a regression?

**Comment by medikoo** [comment]
@Moeriki Yes unfortunately you relied on _bug_ in previous versions.. Resolvers are supposed to _normalize_ the argument which is then passed in _resolved_ form to memoized function.

What you probably wanted to use was `normalize` option. Unfortunately it's not documented well yet, for now see explanation [here](https://github.com/medikoo/memoizee/issues/53#issuecomment-212910309)

I'm closing it, but if still there's something clear please let me know.

**Comment by Moeriki** [comment]
I suspected something like this :) Thanks for the clarifications. I updated my code.

```javascript
const memoized = (func) =>
  memoize(func, {
    normalizer: ([params]) => JSON.stringify(params),
  })
```
