### ISSUE TITLE
Delete question

### ISSUE THREAD

**Issue by hodeyp** [medikoo/memoizee#57]
Is it possible to delete cached entries based upon just the first argument? In my case, I have a memoized function that caches a transform based upon different groupings. When the underlying data is changed I want to delete all of the groupings in the cache for that object but leave all other groupings for other objects intact. Is this possible?

**Comment by medikoo** [comment]
Sorry for late response (lack of proper notification from github made me seen it today).

Similar question was already asked at https://github.com/medikoo/memoizee/issues/55 See the second proposed solution (it's not possible in direct form)
