### ISSUE TITLE
Error: Circular invocation

### ISSUE THREAD

**Issue by maxnowack** [medikoo/memoizee#58]
Sometimes I'm getting `Circular invocation` exceptions. What exactly does this mean and how can I fix it?

**Comment by medikoo** [comment]
It means that for same arguments you call function recursively, and that can't work with memoization.

So e.g. you call memoized function with `6` and then internals of that function call again self function with `6`. With deterministic function (and that should be the case for memoization) it will produce infinite recursion, hence early error
