### ISSUE TITLE
What is cache size unit? 

### ISSUE THREAD

**Issue by vinaykharecha** [medikoo/memoizee#67]
In document i can not find **unit** of **cache size** limit, weather it is KB, MB etc.
Please clarify that it would be very helpful.

**Comment by medikoo** [comment]
@vinaykharecha `size` is purely about how many results to cache. e.g. if `max` is _1000_, then result will be cached only for _1000_ different function calls (on LRU basis).

Library doesn't try to measure how big memory cost is behind certain cache values, but maybe at some point such feature will be introduced

**Comment by medikoo** [comment]
I've also improved documentation, to make that clear https://github.com/medikoo/memoizee#limiting-cache-size
