### ISSUE TITLE
Write library size in README

### ISSUE THREAD

**Issue by shaharmor** [medikoo/memoizee#75]
Hi,

It would be great if the size of the library will be listed in the README for users that want to use it in the browser

**Comment by medikoo** [comment]
@shaharmor library size in browser depends on what functionalities you want to use.
e.g. you can take all of them with:

```javascript
var memoize = require('memoizee');
```

Or just pick ones you want to use with:

```javascript
// Take just base functionality
var memoize = require('memoizee/plain');

// Load 'max' extension
require('memoizee/ext/max');
```

Therefore there's no one answer to that. It will require some configurable generator, which I'm not sure if is really that important feature, taking into account amount of work it may need.

At this point I'm going to close it, as it's not possible to solve it well without significant amount of work, and that seems not justifiable
