### ISSUE TITLE
Will this package maintain cache between app runs?

### ISSUE THREAD

**Issue by oscarvgg** [medikoo/memoizee#91]
I'm writing a command line app that communicates with a server. 
It works like this: Every time the user runs a command, the app requests some data, prints it on the console and finishes with `process.exit`.
Will this package cache the results from the server between command executions? or all the data dies when the app exits?

Thanks.

**Comment by medikoo** [comment]
No, at this point it's only in-memory caching with no options to store and restore from some persistent layer.

Still, this feature was [already requested](https://github.com/medikoo/memoizee/issues/33) and will be provided with upcoming [v1](https://github.com/medikoo/memoizee/issues/73).

I'm going to close it as duplicate
