### ISSUE TITLE
Is there a way to geep cache alive until the provided function does not throw?

### ISSUE THREAD

**Issue by aalexgabi** [medikoo/memoizee#92]
For example I want to keep a cache that avoids executing a db query but I want that the cache is still available if db is down.

1. Call memoized function that returns db a value
2. Db goes down
3. Cache expires
4. Call memoized function that tries to query db which fails but still return the old value from the cache instead of failing

The idea is that sometimes is desirable to have an older value instead of failing.

**Comment by medikoo** [comment]
@aalexgabi it is planned to be provided with v1.

See description of `invalidationSpan` option at `ttl` section in https://github.com/medikoo/memoizee/issues/73

**Comment by aalexgabi** [comment]
@medikoo Thank you.
